---
swagger: 2.0
info:
  title: EventSource API Definition
paths:
  /events/{id}:
    get:
      summary: List event(s)
      description: Retrieve specific event or all if id is not provided
      parameters:
      - name: id
        in: path
        required: false
        type: string
      consumes:
        - application/json
      produces:
        - application/json
      x-amazon-apigateway-integration:
        uri:
          #Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:770212352465:function:eventGetAll/invocations
          Fn::Sub: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:770212352465:function:eventGet/invocations
        responses: {}
        httpMethod: POST
        type: aws_proxy
  /events:
    post:
      summary: Create a new event
      description: Create a new event 
      parameters:
      - name: NewEvent
        in: body
        description: New event details.
        schema:
          $ref: '#/definitions/Event'
      consumes:
        - application/json
      produces:
        - application/json
      x-amazon-apigateway-integration:
        uri:
          #Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:770212352465:function:eventGetAll/invocations
          Fn::Sub: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:770212352465:function:eventCreate/invocations
        responses: {}
        httpMethod: POST
        type: aws_proxy

x-amazon-apigateway-request-validators:
  Validate query string parameters and headers:
    validateRequestParameters: true
    validateRequestBody: false

definitions:
  User:
    properties:
      visitor_id:
        type: string
        description: visitor id of the user
      user_agent:
        type: string
        description: user agent of the user
      anonym_ip:
        type: string
        description: ip address
      device:
        type: string
        description: device type
      logged_in:
        type: boolean
        description: login status
      encrypted_email:
        type: string
        description: encrypted email
  Event:
    properties:
      user:
        $ref: User
      